apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjoge1FXdDFjblZ6UkdWMlpXeHZjR1Z5T21kb2NGOWpVWFJMTmtkU2VHOXNaVXN6TTJSVVRGRTVSR1p2ZFZKbE5rOW9iVFl6Y1hacFpHND19Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCgkicGx1Z2lucyI6IHsKCQkiLXgtY2xpLWhpbnRzIjogewoJCQkiZW5hYmxlZCI6ICJ0cnVlIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
