apiVersion: v1
kind: Secret
metadata:
  name: cinemaabyss-secrets
  namespace: cinemaabyss
type: Opaque
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCSJhdXRoIjogIlFXdDFjblZ6UkdWMlpXeHZjR1Z5T21kb2NGOTBhM2hQUmtkRVlsbHBVa0pOTm1OcWMwRk5hVmxhWVRKeE0xbHZNMW95VjFKdmR6ST0iCgkJfQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiLAoJInBsdWdpbnMiOiB7CgkJIi14LWNsaS1oaW50cyI6IHsKCQkJImVuYWJsZWQiOiAidHJ1ZSIKCQl9Cgl9Cn0K
  # Base64 encoded values
  # echo -n "postgres_password" | base64
  DB_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=